In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedShuffleSplit

In [3]:
# loading data 
data = pd.read_csv("Iris.csv")

In [4]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in split.split(data, data["Species"]):
    strat_train_set = data.loc[train_index]
    strat_test_set = data.loc[test_index]

In [7]:
strat_train_set

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
8,9,4.4,2.9,1.4,0.2,Iris-setosa
106,107,4.9,2.5,4.5,1.7,Iris-virginica
76,77,6.8,2.8,4.8,1.4,Iris-versicolor
9,10,4.9,3.1,1.5,0.1,Iris-setosa
89,90,5.5,2.5,4.0,1.3,Iris-versicolor
...,...,...,...,...,...,...
37,38,4.9,3.1,1.5,0.1,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
3,4,4.6,3.1,1.5,0.2,Iris-setosa

In [8]:
X_train = strat_train_set.iloc[: , : -1]
y_train = strat_train_set.iloc[ : , -1]

In [9]:
X_train

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
8      9            4.4           2.9            1.4           0.2
106  107            4.9           2.5            4.5           1.7
76    77            6.8           2.8            4.8           1.4
9     10            4.9           3.1            1.5           0.1
89    90            5.5           2.5            4.0           1.3
..   ...            ...           ...            ...           ...
37    38            4.9           3.1            1.5           0.1
2      3            4.7           3.2            1.3           0.2
33    34            5.5           4.2            1.4           0.2
52    53            6.9           3.1            4.9           1.5
3      4            4.6           3.1            1.5           0.2

[120 rows x 5 columns]

In [10]:
y_train

8          Iris-setosa
106     Iris-virginica
76     Iris-versicolor
9          Iris-setosa
89     Iris-versicolor
            ...
37         Iris-setosa
2          Iris-setosa
33         Iris-setosa
52     Iris-versicolor
3          Iris-setosa
Name: Species, Length: 120, dtype: object

In [11]:
model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [12]:
X_test = strat_test_set.iloc[:,:-1]
y_test = strat_test_set.iloc[: , -1]

In [13]:
#predict 
predict = model.predict(X_test)
print(predict)

['Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa']

In [14]:
y_test

38         Iris-setosa
127     Iris-virginica
57     Iris-versicolor
93     Iris-versicolor
42         Iris-setosa
56     Iris-versicolor
22         Iris-setosa
20         Iris-setosa
147     Iris-virginica
84     Iris-versicolor
107     Iris-virginica
141     Iris-virginica
104     Iris-virginica
51     Iris-versicolor
7          Iris-setosa
49         Iris-setosa
14         Iris-setosa
69     Iris-versicolor
63     Iris-versicolor
138     Iris-virginica
10         Iris-setosa
140     Iris-virginica
58     Iris-versicolor
134     Iris-virginica
132     Iris-virginica
77     Iris-versicolor
75     Iris-versicolor
18         Iris-setosa
116     Iris-virginica
28         Iris-setosa
Name: Species, dtype: object

In [17]:
actual = y_test.to_numpy()
predicted = predict

count = 0

for i in range(len(actual)):
    if actual[i] == predicted[i]:
        count += 1

print(f"Accuracy: {count * 100 / len(actual):.2f}%")

Accuracy: 100.00%

In [18]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predict)

print(f"Accuracy: {accuracy:.2%}")

Accuracy: 100.00%